### ISSUE TITLE
Сделать активным только на ссылках

### ISSUE THREAD

**Issue by m8rge** [makoni/select-like-a-boss-for-safari#1]
Я часто пользуюсь выделением текста по следующей схеме:
- Двойной клик по слову (оно выделяется полностью),
- Затем не отпуская мыши, веду по тексту, и текст выделяется пословно. 

При такой схеме нет необходимости метится при выделении - выделяются гарантированно слова полностью.

Данный плагин портит данное поведение. Поэтому предложение - ограничить его действие только на ссылках

**Comment by makoni** [comment]
Исправлено (спасибо приславшим Pull-реквесты). Расширение должно обновиться автоматически. Чтобы ускорить этот процесс лучше перезапустить Safari :)
