### ISSUE TITLE
Breaks double-click + drag functionality

### ISSUE THREAD

**Issue by epsimatic** [makoni/select-like-a-boss-for-safari#5]
In OS X, you can double-click any word to select it. If you need to select multiple words, you double-click and drag with left mouse button down.

This functionality gets broken by select-like-a-boss. 

I can't say for sure if it's something Safari-specific or an upstream issue.
## Here're the videos:

Extension is off, double-click+drag works:

![Imgur](http://i.imgur.com/4EUeKo4.gif)

Extension is on, double-click+drag is broken:

![Imgur](http://i.imgur.com/bP78wp2.gif)

**Comment by mbratukha** [comment]
Was already fixed by 7d3ddd584634e5490ffdc9c70a67687db2c7951a.
Update your plugin to the latest version.
