### ISSUE TITLE
Форк для chrome с исправлением

### ISSUE THREAD

**Issue by a-x-** [makoni/select-like-a-boss-for-safari#6]
Добрый день!

В плагине для хрома есть баг.
В режиме эмуляции мобильных устройств плагин сходит с ума.

Я плагины никогда не создавал и не знаю, куда там коней запрягать.

Можно сделать репо плагина под хром?

**Comment by a-x-** [comment]
![image](https://cloud.githubusercontent.com/assets/6201068/6534830/870beb94-c451-11e4-8d8a-599070e7dfcd.png)

**Comment by mbratukha** [comment]
Репо плагина под Хром: https://github.com/Christoph142/Select-like-a-Boss.

**Comment by a-x-** [comment]
Cool! Спасибо

**Comment by a-x-** [comment]
Только там этого кода нет :(

**Comment by makoni** [comment]
ну так атакуйте автора репо для Хрома, чтобы посмотрел сюда и взял отсюда код :)

**Comment by a-x-** [comment]
Спасибо. Я пошёл этим путём 2 дня назад. Пока он не реагирует. 
Может быть есть какие-нибудь его (Dzianis Rusak) актуальные контакты?
Нашёл только G+: https://plus.google.com/105402589926250735322/posts
