### ISSUE TITLE
Support Safari 12 (macOS 10.14)

### ISSUE THREAD

**Issue by euf** [makoni/select-like-a-boss-for-safari#7]
Safari 12 in macOS 10.14 will no longer support `.safariextz` files including those from the Safari Extensions Gallery. The extensions may be distributed only via Mac App Store. Please provide such an option, since _select-like-a-boss-for-safari_ is really great and living without it would be a nightmare.

Source: https://developer.apple.com/safari/whats-new/

Сафари 12 на макОС 10.14 больше не поддерживает расширения `.safariextz`, даже подписанные сертификатом разработчика и загруженные в Галерею Расширений. Теперь можно будет распространять только через Мак Апп Стор. Надеюсь, это расширение появится в Апп Сторе? Жить без него совсем невозможно)

**Comment by rusavv** [comment]
+1

**Comment by makoni** [comment]
Hello everyone. The app containing extension is waiting for review in Mac App Store. I will provide you a link when it will be approved. Hope it will not take much time :)

**Comment by makoni** [comment]
It’s in Mac App Store: https://itunes.apple.com/ru/app/select-like-a-boss/id1437310115?mt=12
